name: Deploy Vite App to cPanel

on:
  push:
    branches:
      - main  # Adjust this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust the version as per your project

      # Move into the webapp directory before installing dependencies
      - name: Install dependencies
        run: |
          cd webapp  # Navigate to the webapp directory
          npm install

      # Build the Vite app inside the webapp folder
      - name: Build Vite App
        run: |
          cd webapp  # Ensure you are in the correct folder
          npm run build

      # Deploy the built files to cPanel using FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          port: ${{ secrets.CPANEL_FTP_PORT }}
          local-dir: webapp/dist/  # Adjust the path to your build folder
          server-dir: public_html/  # Change to your desired directory on cPanel
